#!/bin/bash

# Adjust to match the install location of restprof.
PATH=/usr/local/bin:$PATH

# Backup all profiles.
restprof -a backup

# Keep a week's worth of snapshots for all profiles.
restprof -a forget --prune -l 7
